### ISSUE TITLE
"Chat me" duplicates messages

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-core#114]
**Version info**: 

Delta Chat Core version 0.15.0

**Observation**:

After sending a message to myself, I have one version of the message in my Inbox and another copy in the "Chats" folder.

**Expected behaviour**:
Message only appears once.

**Log**:
```
17:18:40.786 DeltaChat: T2: Job #1 delayed for 0 seconds
17:18:40.788 DeltaChat: T2: Executing job #1, action 800...
17:18:40.790 DeltaChat: T2: Connecting to SMTP-server "smtp.xxxx.com:465" via SSL...
17:18:41.231 DeltaChat: T2: Connection to SMTP-server ok.
17:18:41.231 DeltaChat: T2: Login to SMTP-server as "user@domain.com"...
17:18:41.510 DeltaChat: T2: SMTP-Login ok.
17:18:42.404 DeltaChat: T2: Signal job thread to wake up...
17:18:42.507 DeltaChat: T2: Job #1 done and deleted from database
17:18:42.518 DeltaChat: T2: Executing job #2, action 700...
17:18:42.644 DeltaChat: T4: IDLE has data.
17:18:42.735 DeltaChat: T4: Receive message #493 from INBOX.
17:18:43.343 DeltaChat: T2: Appending message to IMAP-server...
17:18:43.460 DeltaChat: T4: Message already in DB.
17:18:43.476 DeltaChat: T2: Message appended to "Chats".
17:18:43.496 DeltaChat: T4: 1 mails read from "INBOX" with 0 errors.
17:18:43.555 DeltaChat: T4: IDLE start...
```

**Comment by r10s** [comment]
But the message appears only once in Delta Chat? 

I am not sure, if this is a bug IMHO this is a quite usual behaviour in many MUAs - if you send a message to yourself, the MUA saves the copy as usual in the local storage and send another copy via SMTP - when sending to yourself, you get this copy via IMAP later then.

I've just tested this in Thunderbird - if I mail a message to myself, I have the message in the Sent folder and in the Inbox. 

But you're right, this might be confusing as well.

**Comment by r10s** [comment]
on the other hand, it seems very easy to just skip the IMAP part (we cannot skip the SMTP part as this one is REQUIRED for the Autocrypt setup messages, IIRC) - but I am not sure if there are any corner cases.

**Comment by Ampli-fier** [comment]
It confused me (and still does), as this is the only Chat that results in message duplication.
The message is only shown once in DC, hence only expected to exist one time. In my opinion this clutters up the Inbox. User that do not check their Inbox with another MUA would waste storage.

**Comment by r10s** [comment]
It is even more confusing when regarding normal groups with _no members but yourself_:
1.  when creating a group with _no members but yourself_, because of the lack of recipients, only IMAP is done. So, there is only one copy on the server
2. when using the self-sent chat, messages SMTP+IMAP is done and there are two copies on the server
However, maybe 1. can just be regarded as an not typical corner case and for 2. we skip the IMAP part?

**Comment by hpk42** [comment]
IIUC then self-sent was/is introduced for Autocrypt Setup Messages (ASM).  For them, it's important to appear in the normal INBOX so that non-DC clients can pick them up.  If we were to only have one copy then self-sent messages would not be in the Chats folder as well.   Maybe this means that self-sent messages should be handled differently from ASMs?  Like ASMs do not land in the Chat folder ever, and other self-sent messages do not land in the INBOX folder?  (purely looking at this from the user-side, not from how difficult it is to implement)

**Comment by r10s** [comment]
> Like ASMs do not land in the Chat folder ever, and other self-sent messages do not land in the INBOX folder?

Currently also ASMs land in the INBOX (because of SMTP) and in the chats-folder (because of IMAP).

If it is okay that ASMs do not land in the Chat folder (IMAP-upload is skipped), I think it is also okay to do the same for other self-sent messages. As a result, all self-sent message would appear in the INBOX then and are not uploaded to the Chats-folder; there won't be any duplicates any more. 
A typical use case IMHO is to get a photo from the smartphone or to remember an article for later reading on the desktop - the INBOX is quite okay then.

Regarding the corner-case with empty groups: I think it is an expectable behaviour that only IMAP and no SMTP is done, messages sent to a group never land in the INBOX, so it would be even more confusing if they do when the group is empty (resp. contains only the sender) (maybe we should even avoid empty groups to be generated).
