### ISSUE TITLE
imap folder "Chats" does not work with arcor/vodafone

### ISSUE THREAD

**Issue by bitstreamout** [deltachat/deltachat-core#167]
I have created a folder Chats (INBOX.Chats to be exact) but delta chat does not read nor use this.  Therefore I've created a filter rule to move all subjects starting with Chat: and mail from MUA Delta Chat (aka "X-Mailer: Delta Chat" in the E-mail header) to INBOX.Chats.   On the other hand  I see all other mails which reach the standard INBOX (in German named "Posteingang") within delta chat which is exactly *not* what I want.

I'd like to use the imap/smtp server for my family  @ arcor/vodafone with the aliases I've set for my daughter, my wife, and myself. That is that the mail addresses  are not idetical with the login address/name for imap and smtp server which seems to work as the mails from delta chat do reach via smtp and are visible via imap. But how can I change the used INBOX folder for imap?

**Comment by STPKITT** [comment]
Why did you create the folder "Chats" yourself? Didn't Delta Chat create it automatically?

**Comment by bitstreamout** [comment]
Not that I'm aware of.  Should I remove this folder and redo the configuration?

**Comment by testbird** [comment]
Your main problem is that deltachat does not work with providers in general, just a small subset.

https://github.com/deltachat/deltachat-android/issues/28
https://github.com/deltachat/deltachat-android/issues/103
https://github.com/deltachat/deltachat-android/issues/108

(overview https://github.com/deltachat/deltachat-core/issues/117)

> [different alias] mail addresses [that] are not idetical with the login address/name for imap and smtp server

That is actually another valid use case that has not yet been considered in the wiki planning document:
https://github.com/deltachat/deltachat-core/wiki/Use-Cases

But in the best case, maybe DC would just have to filter based on the `To:` according to the account settings?

**Comment by STPKITT** [comment]
Oh I thought those problems had been tackled already.
It still might be useful to know if Delta Chat would work ootb with Arcor/Vodafone, so another try without the user creating a "Chats"-folder beforehand might be useful.

**Comment by bitstreamout** [comment]
Aha ... now it seems to work as I have seen a response from my daughter after 61 minutes on my first "Hallo".   Nevertheless I'd like to see to stop DC to read the standard INBOX to avoid to mix standard E-mails to be mixed with DC chat E-mails do avoid that personal mails can be read that easily.

**Comment by STPKITT** [comment]
:-)
What do you mean with "stop DC to read the standard INBOX"? Stop DC to display standard mails in chat view?

**Comment by bitstreamout** [comment]
Nope ... I see all Emails which had reached the INBOX if I use "Kontaktanfragen" ... this is not very useful in my usecase as Id 'like to avoid that my one of my dependants can reach the mails from the others ... even my own mails I'd like not see here as those are usually not for chatting at all

**Comment by bitstreamout** [comment]
Also ... I actually see no way to clear this huge list ... how to do this?

**Comment by testbird** [comment]
> "Kontaktanfragen" ... this is not very useful in my usecase as Id 'like to avoid that my one of my dependants can reach the mails from the others

Then you will probably all be much happier setting up different accounts. (Especially if you find a provider where deltachat succeeds to create the chat folder in the root, as currently assumed-) Access to all emails is the advantage of aliases and sharing an account.

"Kontaktanfragen" translates to "unapproved emails", it's the place to look at, necessary to find emails from non-Chat contacts that you might want to answer in a chat. See https://github.com/deltachat/deltachat-core/wiki/Use-Cases

**Comment by STPKITT** [comment]
Well, that's how the GUI works (at least for now). The idea is that a Delta Chat user can for example answer E-Mails from somebody who already uses E-Mail for short messages via a standard E-Mail-(web-)client. So it's the nature of the beast that "Kontaktanfragen"/"Contact requests" shows the whole inbox since Delta Chat can't know which E-Mails the user possibly wants to answer via Delta Chat.

Regarding your sentence "as Id 'like to avoid that my one of my dependants can reach the mails from the others": that's because you use aliases instead of separate E-Mail-accounts. You're free to create multiple separate Vodafone accounts since they are free of charge anyway. However I can't recommend Vodafone mail at all, it's very unreliable, their Spam-Filter is awful & can't be deactivated & Vodafone seems to randomly decide to set your account to receive-only claiming that you're sending Spam around. For free accounts T-Online oder web.de are better and web.de works with Delta Chat ootb..

**Comment by testbird** [comment]
@r10s Can't find the issue about using addresses with `+` additions, just like for this issue, to solve it it maybe only be necessary to let DC display only the messages directed `To:` the currently configured (in the future, possibly selected) account. (I saw that a different login name can already be configured in the advanced settings.)

**Comment by testbird** [comment]
A question in regards of users starting to use deltachat: Would you consider it better to understand what the listing shows, if the "contact requests" would be labeled "Unapproved Emails"?  https://github.com/deltachat/deltachat-core/issues/48

**Comment by testbird** [comment]
@r10s: Adding a `To: ` selection to a query or display sounds like a easy thing and a quick fix for alias and `+` address sorting. If DC would be a web project, I'd say it would be more efficient for me if just add that missing filter instead of going through the chores of filing and managing a separate issue.

**Comment by bitstreamout** [comment]
Indeed "Unapproved Emails" seems to be more reasonable as "contact requests"  from standard mails is misleading

**Comment by t-oster** [comment]
your main problem should be solved by #173 and #175, I think the rest of the discussion belongs into another issue
