### ISSUE TITLE
Show, if a message is read by the receiver

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#2]
_Maybe_ we should show, if a message is read by the receiver (in other messengers this is often indicated by two check marks).

_If_ we decide to do so, so called [Return receipts](https://en.wikipedia.org/wiki/Return_receipt), aka Delivery status notifications (DSN) aka Message disposition notifications (MDN) should do the job. See eg. [RFC 3798](https://tools.ietf.org/html/rfc3798) and [RFC 3503](https://tools.ietf.org/html/rfc3503).

Discussions are very welcome on this point.

**Comment by r10s** [comment]
The format would be Disposition-Notification-To: Name <user@example.com>

**Comment by fauno** [comment]
just a thought, only send return receipts when the counterpart is using delta (via the user-agent header?), otherwise it will be bothersome to email client users (thunderbird shows an alert message, for instance)

**Comment by stefan-niedermann** [comment]
@fauno i think there should not be implemented any features that are not based on only-email-standard

**Comment by rizzopablo** [comment]
Please, make it optional, I really like to avoid sending reception/read receipts.
I don't want to know when the other one received or read the message, and I don't want the others to know when I receive/read the messages. I like the fact that you answer whenever you can/want to do it, without pressure. In Argentina we have a new very common expression of disgust: "me clavó el visto!" meaning that you're angry because someone read your message but did not answer inmediately. It's an effect of the anxiety caused by the reception/reading confirmation.

**Comment by r10s** [comment]
Yes, it is planned to make this as an normal option, not even an advanced option - we only removed it for now, at it is not yet clear if we have the time to implement it for version 1.0.

**Comment by r10s** [comment]
Done, Read receipt will be available in 0.9.3 and later. Also see https://github.com/deltachat/deltachat-android/issues/113

**Comment by r10s** [comment]
Some background information: https://github.com/deltachat/deltachat-android/issues/113
