### ISSUE TITLE
support additional contact addresses (and changing defaults)

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#235]
Maybe not the most  pressing issue in general, but in need when it happens:

When contacts change their email address, it would be good to be able to add and remove additional addresses to existing contacts in deltachat, and to select the default for outgoing messages.

**Comment by r10s** [comment]
i also thought about this some time ago, my thoughts were:

1. showing multiple email-addresses of a single contact in different chats _may_ be wanted eg. to divide work/private
2. showing multiple email-addresses of a single contact in different chats may _not_ be wanted by aliases, old addresses etc.

however, if unused aliases, old addresses etc. of 2. appear as a separate chat, they will appear only at the end of a long list and "fade out" as soon as the new address is used. this is transparent for the user and no issue imho.

allowing multiple email-addresses per contact would raise a lot of problems to solve:
- the recipient has to decide to which address he wants to send - a decision that is not always simple
- we would need ui to show from where a given messages was sent
- we probably would need an option to allow sending to several addresses at the same time
- probably, this would also make the key and group management more complicated
- according to experience, probably even more :)
- all this may need additional ui that has to be explained to the user and understood by the user.

compared with that, the current situation seems to be better:
- it is very clear to the user where a message is sent to and received from
- the user needs no additional knowledge
- _KISS - Keep it simple stupid_ :)

the disadvantage may be some cluttered threads - which, however, will also be there if we would offer options to join chats, and need to be fixed by the user

**Comment by testbird** [comment]
Right, very good points.
More problems created than solved can identify a change in the wrong location.

So, didn't we have an issue to allow moving spam/unapproved email/chat messages to other places?
That may also all that is needed to allow to keep the continuity when a contact switches addresses.

**Comment by r10s** [comment]
moved this for discussion to https://support.delta.chat/t/support-additional-contact-addresses/50
