### ISSUE TITLE
[Consolidated] Subject handling

### ISSUE THREAD

**Issue by WinAuthFan** [deltachat/deltachat-core#239]
There are different ideas about what the subject should be and a number of issues have been started on it. #136 , #128 

What I am realizing is that all these ideas have their pro's and con's. What's more, in some conversations, one type of subject could be better. In other conversations, another could be better. This leads me to this idea. Let the user decide. 
* Let the user select a `Default subject template` that applies to all chats.
* Let the user select a `Subject template` for each particular chat. 

There could be a few options for a `Subject template` that the user can select from. The user can also type in their own `Subject template`. 

A subject template is constructed from these elements. (Maybe there could be others too.)
* `[prefix]`. Currently, this is `Chat:`. We could let the user type in anything else they want. We could also have an option to mimic regular MUA's -- on the first email, `[prefix]` is blank, on subsequent emails, it's `Re:` or something else that the user types in. 
* `[topic]`. Currently, only group chats have a topic ("group name"). Allow any chat (group or one on one) to have a topic. 
* `[first few words]`
* `[subject of email being replied to]`. DC uses this currently sometimes, though I am not sure exactly how. 

The current `Subject template` for new emails is: 
* `[prefix]` `[first few words]` for one on one chats
* `[prefix]` `[topic]` `[first few words]` for group chats

Here are different use cases:
* If I am emailing someone more "traditional", I want the subject to look like the subject in a regular MUA. I would set the subject to `[topic]` or `[prefix]` `[topic]` if we can select `[prefix]` to be blank/`Re:` or `[prefix]` `[subject of email being replied to]`. 
* If I don't want to annoy people with the "Chat" prefix and just want to tell them what I want them to know, I would set the subject to `[first few words]`. 
* Sometimes I speak to the same person on different topics, so I would want the subject to be `[prefix]` `[topic]` `[first few words]`, and just change the `[topic]` of the chat every time we start talking about something else. 
* People could set `Subject template` to their preferences, even if it's "unusual". Someone might want their `Subject template` to be "`[first few words]` (`[topic]`)" or "`[first few words]` / `[subject of email being replied to]`"

The advantage of this approach is that all the users are happy, because each user can set the subject to what they want.

**Comment by testbird** [comment]
Maybe it's getting more complicated than needed, and not shortening the default chat subject as it was requested elsewhere.

Have you seen the idea to use ` - ` (blank, minus, blank) as a delimiter sequence not only when displaying a received email message with subject, but also to explicitly specify a subject when writing in deltachat?

If deltachat would just keep non-chat subject, as other MUAs do, it may be possible to realize your different use cases not only per contact (chat) but per message (interaction).

* Chat subjects could default to start with a shorter chat identifier like `-[]` (minus,bracket,optional string,bracket) instead of `Chat:`... .
* This would also allow more room for topic or group pointers `-[DC issues]`... .
* Then let deltachat keep the entire subject, if replying to a non-chat subject.
* And allow deltachat users to manually specify the subject by writing somthing like
   `[subject line test] subject - followed by further text...`

**Comment by testbird** [comment]
`-[]` could be thought of as figuring a chat message bubble, its shortness may allow in-subject chatting in classic MUAs.

=>
* Let deltachat not keep the subject when replying to subject-only messages (answer using default chat message format `-[] text...`.

**Comment by testbird** [comment]
Super bonus: It would allow to add and remove tags to message subjects (within deltachat) that get carried on from message to message. Very handy for a local search or filter function.

**Comment by testbird** [comment]
I remember there is a drafts mechanism for messages. If you would implement a "default draft" for chats, you could still allow to predefine the subject, by having a default draft like `[your prefix] [your topic] - ` or whatever is wanted.

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the linked issues and in the new support forum at https://support.delta.chat
