### ISSUE TITLE
check if outlook and office 356 work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#267]
outlook and office 356 did not worked a long time, however, @Ampli-fier, @t-oster and others figured out things; not sure at the moment what the current state is and what is needed to be done in the core to make this work more reliable.

this issue was originally located at https://github.com/deltachat/deltachat-android/issues/168, however, as related to deltachat-core, i moved it here.

**Comment by Ampli-fier** [comment]
The referenced issue (or, better: the PR that made DC work for me with Office365) was in fact related to the Android version. DC Core worked fine, as the System lib of Cyrussasl contained the required mech(anism).
I successfully used DC Android v0.18.x for quite a while with my Office365 account.
The issue was basically kept open to get confirmation from the Issue reporter(s).

**Comment by r10s** [comment]
so this can be closed?
do you know if office 356 work out-of-the box with only maill+password as credentials? or which settings are needed. maybe we should add some information about this to https://support.delta.chat/t/provider-overview/56/2

**Comment by Ampli-fier** [comment]
I have a company mail address `<user>@<company>.com`.

For me the following settings are needed:

IMAP-Server: `outlook.office365.com`
SMTP-Security: `STARTTLS`

-- Note for the SMTP-Server --
All three server worked: 
`smtp.office365.com` or 
`smtp-mail.outlook.com` or
`outlook.office365.com`.

The latter is automatically used by DC v0.20.0 = same as IMAP-Server.

The forum page needs an update - I can do when account activation for the forum is back working.
I'll close this issue here.

**Comment by r10s** [comment]
thanks, @Ampli-fier 
dc_configure() automatically tries STARTTLS-on-port-587 if SSL-on-port-465 has failed - so, does you office account work with just the default credentians?

wrt forum: your login should work, i've added you manually.
(however, could not make you a moderator yet as for this also email sending is involved ...)

**Comment by Ampli-fier** [comment]
Thanks, the Forum login worked.

I tried before not to provide STARTTLS for SMTP and got an error (sth. like failed to connect using port 465).

I gave it another try after your post and now it worked two times in a row.

With default credentials you mean `mail address` + `password`? 

So, what needs to be entered is just the credentials and the IMAP-Server `outlook.office365.com`.

**Comment by r10s** [comment]
> So, what needs to be entered is just the credentials and the IMAP-Server outlook.office365.com

cool :) - these are worthful information - maybe you can add them to the forum.

wondering if this could be figured out by autodiscover - does your server provide the a urls

`https://<YOUR-DOMAIN>/autodiscover/autodiscover.xml`

or 

`https://autodiscover.<YOUR-DOMAIN>/autodiscover/autodiscover.xml`

and return a xml-file? (nb: format of this file: https://msdn.microsoft.com/en-us/library/bb204278(v=exchg.80).aspx )

at least theoretically, [these files are parsed and understood by delta chat](https://github.com/deltachat/deltachat-core/blob/master/src/dc_configure.c#L250), however, this seems not to be well tested yet - might be that the parsing just fails.

**Comment by Ampli-fier** [comment]
None of the links exist, not with https nor with http.

**Comment by r10s** [comment]
> None of the links exist, not with https nor with http.

thanks for checking :)
so, users using office365 as you do have to add the imap server manually, if this is documented in the provider overview, i think it is fine for now.

however, of course, if needed, webmasters that use office365 could create a autodiscover or autoconfigure file to make the setup process for their users easier :)
