### ISSUE TITLE
Some ideas: DeltaChat for PC

### ISSUE THREAD

**Issue by N3tt3rm4n** [deltachat/deltachat-core#30]
Hey guys, today I discovered DeltaChat and I think that it is fantastic. The aim of the project is what I have always dreamt of, but never managed to find something. Together against WhatsApp! *\*eheem, back to the topic now*\* :blush:
I know that this project has a lot to do, but here's jut an idea: How about making a Desktop client for DeltaChat? I think that would be really great, a kind of slim email client for PC... And maybe a Website for using DeltaChat? Ok, I'm dreaming again, please do not let yourselves get disturbed by me, these are just some ideas in case you are bored :grinning:

**Comment by kskarthik** [comment]
Yes, It would be nice. But, not dev yet started https://github.com/r10s/deltachat-desktop

**Comment by r10s** [comment]
I would also like to have Desktop client, I would prefer Qt which would allows us to target Windows, Mac as well as Linux, but I'm not stuck to this. Maybe existing frontends can be used as a base (Telegram maybe?).

The effort would be less than for the android app as the "core" can be used "as is" and the desktop needs _not_ to think about implementation details as IMAP, SMTP, PGP, Groups and so on.

However, in fact, currently, there is no developer really starting this part and I fear I am fully occupied by Android and the Core Development.

**Comment by kskarthik** [comment]
Using telegram desktop UI as base is the much efficient approach we have with given minimal resources.

**Comment by r10s** [comment]
Only if the code itself is okay and re-usable. This was not always the case for the Android App.

**Comment by kskarthik** [comment]
I just saw the code of tdesktop. Better we come up from scratch as we have fewer options. Be as lightweight as possible. How about GTK ?

**Comment by r10s** [comment]
IMHO GTK is not the first choice for cross platform development targeting also Windows and Mac, however, I'm no GTK developer, so maybe I'm wrong.

**Comment by haeckser** [comment]
Hi,
I tried to start this task with telegram UI (a proposal from r10s) and after some evenings was able to compile it (ubuntu). Unfortunately, it is a big piece for start (not the ui, more the backend and all its dependend packages it is based on). Due to trouble with the delta chat backend (no access to any mail provider from (only) my PC) I was blocked and stopped right here.  I never started to analyze the UI code to start replacing the backend calls, but maybe I will start another try - at least to separate the ui and backend as a first proposal.
if the android backend is also based or inspired by telegram, we might transfer a lot of adapted code (to  delta chat backend from android) to the qt version by searching for the delta chat backend calls.

Maybe I have a free evening this week ..

**Comment by r10s** [comment]
Thank you for your work so far.

To your question: No, the Android backend is neigher based nor inspired by telegram. Only the Android frontend is.

But, in fact, the backend (the core) has some dependencies: sqlite, openssl, libetpan, pthread, zlib, ... it may take some evenings to figure this out, I know ...

**Comment by STPKITT** [comment]
Just from an end-user perspective I'd very much prefer Qt.

**Comment by kollokollo** [comment]
Maybe it is not necessary to port it. One could use Anbox to run it on a desktop computer (like Ubuntu linux). I tried, but the installation of anbox failed. But maybe they fix these problems in future.

**Comment by r10s** [comment]
https://anbox.io/ looks promising. Do you know if there are also Mac/Windows ports planned/available?

**Comment by haeckser** [comment]
Hi,
I have checked ANBOX for Ubuntu Linux.
It is working fine - except the response time for the keyboard is slow.
Nevertheless, it just takes me 2 commands in the terminal and anbox was installed and delta chat added to anbox.
I did exactly what is described in https//anbox.io -> gettting started.
I looked for emulators for Windows and MAC and found NOX player. But in opposite to anbox which is really open source, NOX is paid explicit by your data.
And on the other side, delta chat is yet another email client - is it really required for the desktop if the main benefit (private, no server) is turned into opposite by an emulator?
There are other emulators like Andy and Bluestack (for Windows). Andy seems to be freeware but with a big footprint (based on Virtualbox).
I would like to adapt the web pages related to Linux / PC desktop giving the hint, that up to the moment someone is implementing a qt version, the focus is on android and release 1.0, but emulators can be used
OK? 
Does anyone have the environment to give feedback related to ANDY on PC and other emulators?

**Comment by r10s** [comment]
> I would like to adapt the web pages related to Linux / PC desktop giving the hint, that up to the moment someone is implementing a qt version, the focus is on android and release 1.0, but emulators can be used
> OK?

That would be great. You can either [add sth. to the FAQs](https://github.com/deltachat/deltachat-pages/blob/master/en/help.md) or [write a blog posting](https://github.com/deltachat/deltachat-pages/blob/master/README.md#how-to-create-a-new-blog-post). Or both :)

**Comment by r10s** [comment]
This was fast - thank you very much for your three Pull-Request which are now visible at:
https://delta.chat/en/2017-10-02-desktop-emulators
https://delta.chat/en/help#delta-chat-on-linux-desktop
https://delta.chat/de/help#delta-chat-auf-dem-linux-desktop

**Comment by hpk42** [comment]
just in to report that anbox/delta on ubuntu works fine, wooohooo! 

just a little high keyboard latency as already noted.  thanks for the hint! i can finally use delta on my linux machine ... and anbox seems to be the right approach for this, am kind of trusting the approach more than "regular" android running in a VM.

Wrt to windows/mac ... could Anbox run in an ubuntu VM on those platforms?  As anbox itself is not run through emulation but uses the linux kernel directly (it compiles kernel modules), it's roughly the same in efficiency as those solutions mentioned above which use a VM layer on windows/mac to run android apps.

**Comment by phormanns** [comment]
what about writing a plugin for libpurple (used in pidgin, adium, instantbird and others)?
here the telegram plugin as an example: https://github.com/majn/telegram-purple

**Comment by luisfsr** [comment]
I tried to run DeltaChat through anbox but anbox failed on my ubuntu linux. I wonder if it would not be too much trouble to the average user showing anbox as the default desktop installation, and thus, making DC look less appealing (anbox is still it is too techie).  At this point I'm running DC using genymotion (which is also too techie). IMHO it should remain simple to the end user, as simple as using cryptography in DC (which is super simple in the context of DC). I like the idea of a plugin for pidgin (or maybe a plugin for thunderbird) as pointed by @phormanns . Unfortunately I can't contribute with coding, since I'm not a programmer.

**Comment by r10s** [comment]
see also https://github.com/deltachat/deltachat-android/issues/199

**Comment by JonasDralle** [comment]
tbh I don't see a use case.
DeltaChat is a mail agent so for your desktop needs maybe use Thunderbird or mutt?

**Comment by drequivalent** [comment]
DeltaChat is a messenget that uses mail as a medium. It's all about presentation, and UX is the key.

Telling user "f you, go spend next few hours setting up your mail client for us" is no way to treat a user.
(as is "f you, go use an emulator").

Delta has the right idea, may be the best idea of all free software messengers - make the best of what's already available to the user, do not demand of them anything beyond what they already have. This is why Telegram won. This is why What'sApp won. All they ask of you is a phone number that you already know. And they all have desktop clients.
But they are centralized and closed, thus insecure by default.
Delta needs a legit desktop app. Preferably even with the ability to import settings from Thunderbird/Outlook/Evolution/Claws/whatever

**Comment by drequivalent** [comment]
> user unfriendly
That is the key. Nobody's gonna use it until it's user friendly.

It doesn't matter how feature-rich the messenger is, when nobody's using it. Lowering the entry barrier is the only option.

**Comment by JonasDralle** [comment]
Right now Delta.Chat is primarily an unstable android client. Development focus should be on building a reliable android client (this includes the new smtp handling which needs to be added to the core), then constructing an iOS counterpart and _only then_ one can consider alternative platforms like PC / Windows Phone / ...

**Comment by testbird** [comment]
If it works out Email-chat will become available for a number of standard chat applications (in different desktop envirionments) with this plugin development: https://gitlab.com/lupine/purple-plugin-delta

**Comment by drequivalent** [comment]
@testbird Cool. Too bad most of libpurple clients are outdated, but still cool.

**Comment by hpk42** [comment]
On Sun, May 13, 2018 at 10:26 -0700, Jonas Dralle wrote:
> Right now Delta.Chat is primarily an unstable android client. Development focus should be on building a reliable android client (this includes the new smtp handling which needs to be added to the core), then constructing an iOS counterpart and _only then_ one can consider alternative platforms like PC / Windows Phone / ...

reliability is certainly a goal, i created a wiki page to
list some initial thoughts on it. 

https://github.com/deltachat/deltachat-android/wiki/Reliability

There is the question of which users to care first for. 
Delta must not neccessarily compete with "all" whatsapp or signal
users for the time being.  It's beta and probably remaining 
experimental for more time.  Maybe in 2019 it could reach 
more maturity and then address larger audiences.  One 
problem here is the "oh no, not another messenger please" gut 
feeling of many. However, if you can do things with Delta that you
can't do otherwise, it's a different game. For example offering
"standalone desktop messaging, no mobile required". 

Appreciating your push for "stability first, ios next
and then the rest" ... but don't see it as excluding other
things happening which are interesting in their own right ...
Lastly, "Delta chat" is what folks engaged with it contribute
and make happening together. 

If you like to discuss overall strategies rather than 
the issue here, please rather send to the mailing list.

**Comment by singpolyma** [comment]
One idea might also be to implement a libpurple or telepathy module for deltachat, so all the existing UIs in those ecosystems could be used.

**Comment by momedo** [comment]
Delta Chat is a nice project. It is a derivation of the POPTASTIC Function described here:
https://sf.net/projects/goldbug/files/bigseven-crypto-audit.pdf

As far as it is to see, the delta client uses java implementations of crypto libs, which are in the key format not so easy to find in Qt (c++) for a desktop client.

But there is a way to use a desktop client (in Qt) for this chat, if the function FireChat-Channel from this java application would be added to delta: https://github.com/textbrowser/smoke

Then also the given Qt Clients could be used to chat over FireChat with Delta Clients.
Just an idea for a possible solution, if some java code is added to delta for the fire chat, then not a new Qt client with the crypto lib problems need to be established from scratch.
would save a lot of work, if delta is extended with some java lines and not a new desktop client is created, as there are desktop clients in Qt are given, which can host a FireChat Channel.

thanks for an evaluation/consideration.

**Comment by r10s** [comment]
Delta Chat is not a derivation of "POPTASTIC Function".

**Comment by r10s** [comment]
development has started: https://github.com/deltachat/deltachat-desktop :)
