### ISSUE TITLE
add a function that shows the encryption state of the chat?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#343]
if addition to `dc_msg_get_showpadlock()` we need sth. as `dc_chat_get_showpadlock()` to check out if a lock should be draw on the "send" button.

in older versions, `dc_msg_get_showpadlock()` imply that subsequent messages are also encrypted, however, this was not really understood by the users. 
also, this has the confusing disadvantage that the state of a messages changes if the user disables the e2ee-setting (as subsequent messages are no longer encrypted then ...).

**Comment by hpk42** [comment]
in opportunistic chats there might be small dragons here UI-wise ... if i am starting to type a message and just before i hit "send" the send button changes from default-encrypt to default-not-encrypt because there was a new non-encrypted messages coming in -- it's a bit surprising/annoying maybe.  But it's an edge case, admittedly.   So maybe when "send" is actually clicked, it should tell the underlying code what to do (encrypt/not-encrypt) even though the opportunistic autocrypt states for the recipients might have changed meanwhile ...

**Comment by r10s** [comment]
closing this for now, changes in this area should be driven by ui/ux, not necessarily function-wise.
