### ISSUE TITLE
Introduce helper to get at "Received" mime headers for incoming messages

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#365]
For performance debugging of the network messaging pipeline it'd be very handy to have a function that returns all ``Received`` headers and the ``Date`` header if possible, for a given incoming message.  
A possible naming is `dc_get_perf_mime_headers_incoming(msg_id)`.  This should return a multi-line string with at least the Received or Date headers (and maybe additional headers). For outgoing message this should return NULL. 

note that the `incoming` suffix is there because in the future we also might want to get Received-headers for "outgoing" messages by requesting them from the receiver which could probably send it back as part of the read-MDN.  Once this issue is resolved, another issue or PR could note/address the outgoing case. 

Even with just the "incoming" case covered we could have two bots sending each other messages through the same or two e-mail providers and measure the different hops.  this can be used for systematic provider-analysis given we have test accounts with them.

**Comment by r10s** [comment]
@hpk42 just had a look at this.

there seems to be no easy way to get the raw headers from libetpan (i did not really expected this), however, i noticed that [there is already an undocumented debug option called "save_eml"](https://github.com/deltachat/deltachat-core/blob/master/src/dc_receive_imf.c#L1458): if `dc_set_config(context, "save_eml", "1")` was executed, all received headers and messages are written rawly to files. unfortunately, it is hard to guess from the msg_id to the filename, however, we could change this by naming the files as  `msg_id_<msgid>.eml`.

- the files are written to the blob-directory, so it should be easy to access them. 
- header parsing should not be more complicated as if one gets only the header
- the feature may become handy also in other situations
- using a switch to start saving these files might also be a good idea. this way, they are not saved by default and leave maybe unwanted traces on the user's device.
- using files instead of the database is also not that bad. esp. when it comes to the planned trimming of chats, it is needed to scan the blob directory for unused files; this way, the raw files may get deleted eg. after a day or so
- it is already there - and of course, we can tweak things later :)

what do you think?

**Comment by hpk42** [comment]
On Mon, Oct 15, 2018 at 04:34 -0700, björn petersen wrote:
> @hpk42 just had a look at this.
> 
> there seems to be no easy way to get the raw headers from libetpan (i did not really expected this), however, i noticed that [there is already an undocumented debug option called "save_eml"](https://github.com/deltachat/deltachat-core/blob/master/src/dc_receive_imf.c#L1458): if `dc_set_config(context, "save_eml", "1")` was executed, all received headers and messages are written rawly to files. unfortunately, it is hard to guess from the msg_id to the filename, however, we could change this by naming the files as  `msg_id_<msgid>.eml`.

and <msgid> is delta's integer, not the mime "Message-Id", right? 

> - the files are written to the blob-directory, so it should be easy to access them. 
> - header parsing should not be more complicated as if one gets only the header
> - the feature may become handy also in other situations
> - using a switch to start saving these files might also be a good idea. this way, they are not saved by default and leave maybe unwanted traces on the user's device.
> - using files instead of the database is also not that bad. esp. when it comes to the planned trimming of chats, it is needed to scan the blob directory for unused files; this way, the raw files may get deleted eg. after a day or so
> - it is already there - and of course, we can tweak things later :)
> 
> what do you think?

i suggest to still introduce a ``dc_get_saved_eml`` function which
returns a char* instead of fiddling with filesystem-paths. This allows
to change the implementation/locations etc later. It's fine to require
"save_eml" config to be set for this (otherwise NULL is returned on 
from the API call).
