### ISSUE TITLE
(option to) copy files directly when dc_msg_set_file() is called. 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#374]
currently, when you do set_file() you need to make sure that the file remains in place until the smtp-job gets around to transmit the thing.  Is there a particular reason to delay the copy to some uncertain future? Most of the time these files are <1MB and that should be very quick to copy on any device, no?

**Comment by r10s** [comment]
thinking it over, i think it makes totally sense to have a more reliable and predictable way here. probably also better for bots - generate file - send file - delete file.

**Comment by hpk42** [comment]
On Tue, Oct 09, 2018 at 07:41 -0700, björn petersen wrote:
> thinking it over, i think it makes totally sense to have a more reliable and predictable way here. probably also better for bots - generate file - send file - delete file.

that's exactly my use-case.  

I'd even be fine to "move" the file when "set_file" is called
but that probably doesn't match android's use cases. 

alternatively, I could try to fish for events (SMTP_delivered) but i suspect it's
involved also because the smtp-delivered does not reference the msg and
even if the msg can be derived it's not clear it still knows about
the "original" file location.  It seems simpler to just copy.
If in doubt i guess in Java you can call set_file() in a ui thread, no?

**Comment by r10s** [comment]
i do not want to do the copy on dc_msg_set_file() as the dc_msg_t object (as well as dc_chat_t and dc_contact_t) is just a "dumb" object without much logic on its own.

the dc_msg_t object should be usable for preparing things - and if the dc_msg_t is discarded without being sent, there should be no change on the db.

however, the dc_send_msg() can be easily done in a thread in java, it's just a "one-liner" as `new Thread(()->{dc_send_msg();}).start()` - i do this already for other stuff, eg. for the setup message or for mass-deletion.

--> so, i would suggeste to copy files in dc_send_msg() (and maybe in dc_save_draft())

**Comment by hpk42** [comment]
On Wed, Oct 10, 2018 at 04:39 -0700, björn petersen wrote:
> i do not want to do the copy on dc_msg_set_file() as the dc_msg_t object (as well as dc_chat_t and dc_contact_t) is just a "dumb" object without much logic on its own.
> 
> the dc_msg_t object should be usable for preparing things - and if the dc_msg_t is discarded without being sent, there should be no change on the db.
> 
> however, the dc_send_msg() can be easily done in a thread in java, it's just a "one-liner" as `new Thread(()->{dc_send_msg();}).start()` - i do this already for other stuff, eg. for the setup message or for mass-deletion.
> 
> --> so, i would suggeste to copy files in dc_send_msg() (and maybe in dc_save_draft())

fair enough. So when dc_send_msg() returns the original file can be safely deleted.

**Comment by r10s** [comment]
> fair enough. So when dc_send_msg() returns the original file can be safely deleted.

jupp, i will do a pr

**Comment by r10s** [comment]
reminder for myself:

we have the possibility to flag files attached to messages as being "in creation".
these messages are not sent until the file attached is "ready".

this method is currently only used for videos: if a user sends a video, this video must be recoded before it can be sent. after that, it goes to smtp as usual. for the user, there is so special wait dialog or different handling, it "just happens".

technically, these "in creation" files are handled very simple: if the ui wants to send a file `bigvideo.mp4` it just has to create the file `bigvideo.mp4.increation` while the real video is being created. once done, the `.increation` file can be deleted; this is then recognized by the core and the message is really sent.

this process makes sure that the file being increation is completely in dependent from the database: eg. the user can already forward it to different users or groups (this is a typical usecase: record a video and send it to a bunch of different groups)

for this issue, the only important thing is that the file being created should already be in the blob directory so that there is no need to copy it later - otherwise, things will get complicated as a delayed copy is needed anyway. however, currently, i cannot imagine why the ui would want to create it elsewhere, so, at least for now this is fine. we should only document this behaviour and maybe return an error otherwise.

however, all this won't affect bots but only ui recoding videos (i think images are fast enough on recoding).
