### ISSUE TITLE
Folder meanings 

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-core#41]
In the file [mrimap.c](https://github.com/deltachat/deltachat-core/blob/master/src/mrimap.c) you have defined "**meaning**" categories for the mailbox folder:

`#define MEANING_NORMAL       1`
`#define MEANING_INBOX        2`
`#define MEANING_IGNORE       3`
`#define MEANING_SENT_OBJECTS 4`

You maintain a list of hardcodes strings to identify the meaning.
1) Maybe this issue can be used to get feedback from other people for other languages that are not yet in the list.

2) I noticed, that my **Sent** folder is probably not matched correctly. I get this info in logcat:
`DeltaChat: T4: 0 mails read from "Sent Items" with 0 errors.`

3) I also see this message in logcat:
`DeltaChat: T4: Cannot fetch message list from folder "Archive".`
Maybe the Archive folder should be added to the IGNORE category?

**Comment by r10s** [comment]
Well, the concrete folder names are only a fallback. 

By default, Delta Chat uses XLIST, see https://github.com/deltachat/deltachat-core/blob/master/src/mrimap.c#L99 (the strings in this block are "flags" that are equal in every language) Only if the XLIST extension is not supported by the server, the names are used (I'm not sure for how many servers this is the case, all my test servers do have XLIST - IIRC, the fallback was written prior to the XLIST code.

But you are right, if we have this fallback, we should also allow strings from other languages here.

**Comment by Ampli-fier** [comment]
Thanks for your explanation.
It would be nice to know how often the fallback is actually needed (maybe it does not make sense to maintain it at all).  You could think about implementing a message to the user in case XLIST is not supported. Like "Please send a message to the developer of Delta Chat ...". As long as DC is in Beta state.

What about the _Archive_ folder, is it not ignored on purpose? 
I would have thought that messages that go there are never part of a conversation.

**Comment by r10s** [comment]
Archive is not ignored.
Delta Chat scans all folders but the exceptions above about every half hour to catch messages moved by automatic filters or messages send by yourself from other devices.
The INBOX is watched via Push (resp. IMAP-Idle).

**Comment by r10s** [comment]
Coming back to this issue ...

> I noticed, that my Sent folder is probably not matched correctly. I get this info in logcat:
DeltaChat: T4: 0 mails read from "Sent Items" with 0 errors.

This is normal, the "sent folder" is only the place where Delta Chat moves messages sent to. If you sent a message on another device, you will see this message on the other devices, too. Therefore it is needed to scan the folder from time to time. 

**So, what's left?**

> Maybe this issue can be used to get feedback from other people for other languages that are not yet in the list.

well, the issue is here half a year without feedback. Maybe we should try to collect local foldernames using the normal translation workflow? Or maybe there is a more complete list somewhere in the internet? however, I am also not sure how important this all is - maybe XLIST (returns the folder meanings by design and is supported by delta) is already widely supported.
