### ISSUE TITLE
housekeeping of blob directory

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#484]
currently, files in the blob directory are not deleted if _chats_ are deleted (they are deleted if _messages_ are deleted).

the plan was to add a garbage collection that deletes unreferenced files in the blob directory from time to time, however, it's just not done yet.

one reason for the delay is the rough idea of an at-rest-encryption of the whole database (#194). for this purpose, it might be easier to move all blob files to a sqlite table before - this way, there won't be the need to encrypt files separated and it would probably also make the housekeeping a bit easier.

also, having the blobs already in the database would make backup export/import much easier as it would be simply a file copy - no need for extra space needed for a VACUUM command.

quesions: are there experiences with sqlite handling large databases of several gb in size? (2-4 are not uncommon)
esp. experiences on mobile devices?

this would be very interesting :)

**Comment by Jikstra** [comment]
> also, having the blobs already in the database would make backup export/import much easier as it would be simply a file copy - no need for extra space needed for a VACUUM command.

BLOBS in a database is generally bad practice and definetly slower. The only problem i see is for the encrypted database. We definetly also want the files to be encrypted, with sqlcipher this would be done in the same step. Maybe we should do some benchmarks on this?

**Comment by CompuRoot** [comment]
Huge SQLite database isn't an issue. We successfully managing database that's 560Gb in size without a problem. The only thing that one need to keep in mind, is that SQLite won't accept single blob if it bigger than 1Gb in size. This is hardcoded limit. Also, deleting records from SQLite database - won't reduce size of database, so if one would attempt to reduce space on mobile devices by deleting some messages with attachments , this action will fail unless VACUUM command would be used after such action which I think isn't a good idea since it CPU hungry and time consuming operation.

**Comment by testbird** [comment]
> currently, files in the blob directory are not deleted if chats are deleted (they are deleted if messages are deleted).

Why does deleting an entire chat not delete the contained messages?
That would seem like a more consistent housekeeping principle to me, with no need for garbage collection, regardless if blobs are in the database or the filesystem.

https://github.com/deltachat/deltachat-core/issues/210 "deleting last chat left artifacts behind on server"
https://support.delta.chat/t/clear-chat-function/163

**Comment by testbird** [comment]
> messages are deleted when chats are deleted.

Sorry, didn't know messages get deleted *locally* already,  so I misunderstood your words based on what I experienced.
They were not deleted *on the server* (user visible), or is this corrected already? May be a good part for the new syncing enablements.

**Comment by csb0730** [comment]
I want to add some thoughts to @CompuRoot's comment:

If blob files would be stored in database the database file would be much bigger than now. My local experience is that it will reach approx 10x size of the messages only db file!

I suspect that under this conditions _vacuum_ will be an issue because of the needed memory (> 2x db size) for doing that. And keep in mind that then the db will be really much bigger than now! This quickly can run into an issue at devices where storage is short.

I would recommend to let the blobs as they are: files into a directory.
