### ISSUE TITLE
Some meson pro should review the mac modifications

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-core#512]
Some things i think are wrong
- [ ] I'm using `host_machine.system()` instead of `target_machine.system()` which will probably fail on cross compiling setups (not really important for the moment)
- [ ] We shouldn't do a libetpan on mac as it will fail anyway, maybe forbid it?

Probably some more stuff

**Comment by flub** [comment]
Wrt #505 I guess. Will try to at some point

**Comment by Jikstra** [comment]
@flub yes that's the one :)

**Comment by flub** [comment]
Looking through git history it seems #157 is the reason >= 1.8 was used.  Looking at that it seems correct, it does not exist in 1.6 which was released in Oct 2014.  So why you're happy with this version on OSX I'm not sure...

I assume we shouldn't use a fallback etpan on mac?

We're indeed not supporting cross-compilation yet, so that doesn't matter.
