### ISSUE TITLE
Creating a .so for deltachat-core

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-core#78]
Heyo,

I want to create a .so file for deltachat-core, for the node bindings. I spent two hours or so trying to get it all to compile with not much luck, having a ton of issues -- I haven't worked with C in years...

I wonder if someone could help me out by creating a Makefile (or autogen.sh?) for this project. I tried converting the codeblocks file into a Makefile using cbp2make, but having one issue after another trying to get all of the libraries linked up on my malconfigured mac 

Thanks a ton

**Comment by r10s** [comment]
Hi karissa,

thanks for trying things out. i think the problem is not C, it's the environment, dependencies, configuration, bindings and such things ... the classical build tools also does not make things easier in many cases IMHO, i also have very few experiences with them.

however, floris also needs a .so for the python binding, i think we will got for [meson](http://mesonbuild.com/) to create a .so library. we'll meet these days on 34C3 hopefully.

**Comment by karissa** [comment]
The environment, dependencies, configuration give C errors that turn into wild goose chase/scavenger hunt every time it seems, which gets pretty old after a while! great, thanks a bunch for your help!

**Comment by r10s** [comment]
i think at least the .so is available now and can be created using the commands given in the README.
