### ISSUE TITLE
Overhead, automatic shipping of GMail drafts via Delta.Chat

### ISSUE THREAD

**Issue by JWvoss** [deltachat/deltachat-core#99]
Gmail is one of the mailer issue groups. An observation. I write with Googlemail a design that I will not yet send, so show me Delta 0.9.9 someday that this draft was sent as a normal message - receipt included. I noticed that twice in unencrypted messages.

**Comment by r10s** [comment]
maybe this is related to #41

**Comment by r10s** [comment]
since https://github.com/deltachat/deltachat-core/pull/407 (available in android-dev and in the upcoming f-droid-release) Delta Chat only downloads messages from the INBOX and from the DeltaChat folder.

other folders are no longer touched and therefore draft-folders that are not recogised as such are also no longer regarded.
